name: FarragoFiction
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: jadedResearcher <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0

web:
  compiler:
    debug: dartdevc